spring:
  application:
    name: servicio-items
server:
  port: 8082

client:
  rest:
    application:
      name: servicio-productos
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
